name: astro
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.1
  get: ^4.6.5
  flutter_svg: ^2.0.7
  file_picker: ^5.5.0
  get_storage: ^2.1.1
  http: ^1.1.0
  webview_flutter: ^4.4.1
  google_fonts: ^6.1.0
  pinput: ^3.0.1
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  # connectivity: ^3.0.6
  # firebase_core: ^2.4.1
  # firebase_messaging: ^14.2.1
  # flutter_local_notifications: ^14.1.1
  # path_provider: ^2.0.8
  # url_strategy: ^0.2.0
  # pin_code_fields: ^7.3.0
  # geolocator: ^9.0.2
  # google_maps_flutter: ^2.1.5
  # google_maps_flutter_web: ^0.4.0+5
  # flutter_typeahead: ^4.3.7
  # carousel_slider: ^4.0.0
  # shimmer_animation: ^2.1.0+1
  # image_picker: ^0.8.5+3
  # image_picker_ios: ^0.8.5+6
  # universal_html: ^2.0.8
  # flutter_inappwebview: ^5.7.1
  # flutter_widget_from_html: ^0.8.5
  # fwfh_selectable_text: ^0.8.3+1
  # flutter_html: ^3.0.0-alpha.5
  # url_launcher: ^6.1.2
  # http: ^0.13.4
  # pointer_interceptor: ^0.9.0+1
  # phone_number: ^1.0.0
  # country_code_picker: ^2.0.2
  # cached_network_image: ^3.2.1
  # photo_view: ^0.14.0
  # image_compression_flutter: ^1.0.2
  # dotted_border: ^2.0.0+1
  # share_plus: ^6.3.0
  # fwfh_text_style: ^2.22.8+1
  # expandable_bottom_sheet: ^1.1.1+1
  # google_sign_in: ^5.4.2
  # google_sign_in_web: ^0.10.2
  # flutter_facebook_auth: ^5.0.1
  # flutter_animarker: ^3.2.0
  # sign_in_with_apple: ^4.3.0
  # intl: ^0.18.0
  # just_the_tooltip: ^0.0.12
  # flutter_slidable: ^3.0.0
  # meta_seo: ^3.0.5
  # animated_flip_counter: ^0.2.5


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/png/icons/
    - assets/png/images/
    - assets/svg/images/
    - assets/svg/icons/
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
