import 'package:get/get_navigation/src/root/internacionalization.dart';

class LanguageClass extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "Hello Astrologer": "Hello Astrologer",
          "Find an Astrologer": "Find an Astrologer",
          "call": "call",
          "notification": "notification",
          "Chat": "Chat",
          "Busy": "Busy",
          "support": "support",
          "Bank Details": "Bank Details",
          "Profile": "Profile",
          "home": "home",
          "services": "services",
          "Free Services": "Free Services",
          "Select Language": "Select Language",
          "Hindi": "Hindi",
          "Earning History": "Earning History",
          "Reviews": "Reviews",
          "Contact Us": "Contact Us",
          "About Us": "About Us",
          "Followers": "Followers",
          "Terms & Conditions": "Terms & Conditions",
          "Privacy Policy": "Privacy Policy",
          "FAQ": "FAQ",
          "Sign Out": "Sign Out",
          "From date": "From date",
          "End Date": "End Date",
          "Generate Statement": "Generate Statement",
          "find order": "find order",
          "Duration": "Duration",
          "Transaction ID": "Transaction ID",
          "Promotional Minutes": "Promotional Minutes",
          "Earning": "Earning",
          "Billable Minutes": "Billable Minutes",
          "Submit your query": "Submit your query",
          "Call": "Call",
          "Mail": "Mail",
          "Name": "Name",
          "LANGUAGE": "LANGUAGE",
          "Rate per Minute": "Rate per Minute",
          "Expertise": "Expertise",
          "Availability time": "Availability time",
          "Upload profile": "Upload profile",
          "Gallery Images": "Gallery Images",
          "Continue": "Continue",
          "Update Bank details": "Update Bank details",
          "Account information": "Account information",
          "Last updated on": "Last updated on",
          "Beneficiary Name": "Beneficiary Name",
          "Bank Name": "Bank Name",
          "Account Number": "Account Number",
          "IFSC code": "IFSC code",
          "Branch Name": "Branch Name",
          "Cancelled Cheque": "Cancelled Cheque",
          "Download": "Download",
          "Edit Bank Details": "Edit Bank Details",
          "Approved": "Approved",
          "Admin Support": "Admin Support",
          "User Assistant": "User Assistant",
          "Type a mesage": "Type a mesage",
          "Kundali": "Kundali",
          "Horoscope": "Horoscope",
          "Matchmaking": "Matchmaking",
          "Panchang": "Panchang",
          "History": "History",
          "Live Chat": "Live Chat",
          "Search here": "Search here",
          "(Services) Chat": "(Services) Chat",
          "(Services) Call": "(Services) Call",
          "(Services) Busy": "(Services) Busy",
          "Chat Room": "Chat Room",
          "Current": "Current",
          "Help & Support": "Help & Support",
          "Approval": "Approval",
          "Have any issues related to bank details?":
              "Have any issues related to bank details?",
          "Raise request": "Raise request",
          "Submit": "Submit",
          "OR": "OR",
          "Price": "Price",
          "Call Rate": "Call Rate",
          "Chat Rate": "Chat Rate",
        },
        "hi_IN": {
          "Hello Astrologer": "हेलो एस्ट्रोलॉजर",
          "Find an Astrologer": "ज्योतिषी को खोजें",
          "call": "कॉल",
          "notification": "अधिसूचना",
          "Chat": "चैट",
          "support": "सहायता",
          "Bank Details": "बैंक विवरण",
          "Busy": "व्यस्त",
          "Profile": "प्रोफ़ाइल",
          "home": "होम",
          "services": "सेवाएँ",
          "Free Services": "निःशुल्क सेवाएँ",
          "Select Language": "भाषा चुने",
          "Hindi": "हिंदी",
          "Earning History": "कमाई का इतिहास",
          "Reviews": "समीक्षा",
          "Contact Us": "संपर्क करें",
          "About Us": "हमारे बारे में",
          "Followers": "समर्थक",
          "Terms & Conditions": "नियम एवं शर्तें",
          "Privacy Policy": "गोपनीयता नीति",
          "FAQ": "सामान्य प्रश्न",
          "Sign Out": "साइन आउट",
          "From date": "की तिथि से",
          "End Date": "अंतिम तिथि",
          "Generate Statement": "वक्तव्य जनरेट करें",
          "find order": "ऑर्डर ढूंढें",
          "Duration": "अवधि",
          "Transaction ID": "लेन-देन आईडी",
          "Promotional Minutes": "प्रमोशनल मिनट्स",
          "Earning": "कमाई",
          "Billable Minutes": "बिल योग्य मिनट",
          "Submit your query": "अपनी क्वेरी सबमिट करें",
          "Call": "कॉल",
          "Mail": "मेल",
          "Name": "नाम",
          "LANGUAGE": "भाषा",
          "Rate per Minute": "दर प्रति मिनट",
          "Expertise": "विशेषज्ञता",
          "Availability time": "उपलब्धता का समय",
          "Upload profile": "प्रोफ़ाइल अपलोड करें",
          "Gallery Images": "गैलरी छवियाँ",
          "Continue": "जारी रखना",
          "Update Bank details": "बैंक विवरण अपडेट करें",
          "Account information": "खाता संबंधी जानकारी",
          "Last updated on": "अंतिम बार अद्यतन किया गया",
          "Beneficiary Name": "लाभार्थी का नाम",
          "Bank Name": "बैंक का नाम",
          "Account Number": "खाता संख्या",
          "IFSC code": "आई.एफ.एस.सी. कोड",
          "Branch Name": "शाखा का नाम",
          "Cancelled Cheque": "रद्द किया गया चेक",
          "Download": "डाउनलोड करें",
          "Edit Bank Details": "बैंक विवरण संपादित करें",
          "Approved": "अनुमत",
          "Admin Support": "व्यवस्थापकीय सहायता",
          "User Assistant": "उपयोगकर्ता सहायक",
          "Type a mesage": "संदेश लिखें",
          "Kundali": "कुण्डली",
          "Horoscope": "राशिफल",
          "Matchmaking": "मंगनी कराणा",
          "Panchang": "पंचांग",
          "History": "इतिहास",
          "Live Chat": "सीधी बातचीत",
          "Search here": "यहां खोजे",
          "(Services) Chat": "चैट",
          "(Services) Call": "कॉल",
          "(Services) Busy": "व्यस्त",
          "Chat Room": "चैट रूम",
          "Current": "मौजूदा",
          "Help & Support": "सहायता और समर्थन",
          "Approval": "स्वीकृति",
          "Have any issues related to bank details?":
              "क्या बैंक विवरण से संबंधित कोई समस्या है?",
          "Raise request": "अनुरोध करें",
          "Submit": "जमा करें",
          "OR": "या",
          "Price": "मूल्य",
          "Call Rate": "कॉल मूल्य",
          "Chat Rate": "चैट मूल्य",
        }
      };
}
